### ISSUE TITLE
bc mismatch in provisioning app configuration

### ISSUE THREAD

**Issue by tjaeschke** [opendevstack/ods-provisioning-app#16] opened 2018-08-16 06:39 UTC
Currently there seems to be a template mismatch. After importing the provisioning app with tailor I get the following error as soon as a jenkins build has been triggered in the build console:

```
[prov-cd-prov-app-dev] Running shell script
+ oc patch bc prov-app --patch '
   spec:
     output:
       to:
         kind: ImageStreamTag
         name: prov-app:3-8d0fa827
     runPolicy: Serial
     source:
       type: Binary
     strategy:
       type: Docker
       dockerstrategy: {}
    ' -n prov-dev
The BuildConfig "prov-app" is invalid:
* spec.source.git: Invalid value: "": may not be set when binary is also set
* spec.source.binary: Invalid value: "": may not be set when git is also set
```
The pipeline uses the shared-lib latest

**Comment by clemensutschig** [comment] 2018-08-16 06:42
dupe of #15

**Closed by clemensutschig** 2018-08-16 06:42 UTC
Labels: bug, duplicate
