### ISSUE TITLE
ODS Project Provision does not add links to project - because of missing project permissions / roles

### ISSUE THREAD

**Issue by clemensutschig** [opendevstack/ods-provisioning-app#403] opened 2020-04-03 12:10 UTC
**Describe the bug**
Provision a new project - this will work, but no links are created!

**To Reproduce**
Provison a new projevt . and look into the logs
                                                
2020-03-12 17:03:56 loggerFileName=UC402 [http-nio-8080-exec-8] ERROR o.o.provision.util.rest.RestClient - Call failed:                                                                               
org.opendevstack.provision.util.exception.HttpException: Could not POST > https://....../rest/projects/1.0/project/UC402/shortcut : {"errorMessages":["You must have the browse project perm
        at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:51)                                                                                                                
        at org.opendevstack.provision.services.JiraAdapter.addShortcutsToProject(JiraAdapter.java:339)                                                               
        at org.opendevstack.provision.controller.ProjectApiController.addProject(ProjectApiController.java:187)                                                                                       
        at sun.reflect.GeneratedMethodAccessor199.invoke(Unknown Source)                                                                    

**Expected behavior**
Links created as advertised

**Affected version (please complete the following information):**
 - OpenDevStack [e.g. 1.2x - master]

**Additional context**
The reason is that the user that creates the project is only set as owner (and NOT as user / team member or alike) - and hence lacks the permissions to create the links.

**Comment by clemensutschig** [comment] 2020-05-10 07:40
@stitakis do you Take this up?

**Comment by stitakis** [comment] 2020-05-11 06:11
@clemensutschig I'll do this as next

**Comment by segator** [comment] 2020-05-13 12:34
tech_integration  is admin, but ODS is creating their own permission schemes probably is not set in the  current scheme.

**Comment by clemensutschig** [comment] 2020-05-13 12:38
@segator > that should not be the issue - what global rights has tech_integration?

**Comment by stitakis** [comment] 2020-05-13 12:51
I investigate it a bit today... small update:
Using ProvApp: 
- I was NOT able to reproduce created a new project with "create special permissionset"  
- I was able to reproduce when created a new project without "create special permissionset"

As indicated by Clemens it looks to me that this is related to the global permissions configuration. On BIX, this error is currently not raised.

The ProvApp is not adding any special permission when creating a new provect if flag `create special permissionset` is set to `false`

**Comment by stitakis** [comment] 2020-05-13 13:18
I think I found the problem:
In jira the `project role` called `owner` was not set to the permission `Browse Projects` in the `Default Software scheme`. 
I was able to provision a new project (create special permissionset = false) after adding the role `owner` to the permission `Browse Projects`.

@clemensutschig I'll close this item, for me is jira config problem, ok?

@segator please review my change in jira development environment. Eventually we need to do same change in the other jira envs.

**Comment by clemensutschig** [comment] 2020-05-14 07:11
@stitakis  - please add a line into the doc . and then close this - well done!

**Closed** 2020-06-16 14:59 UTC
Labels: bug, high-prio
