### ISSUE TITLE
De-provision feature for prov-application provisioned components

### ISSUE THREAD

**Issue by thowerner** [opendevstack/ods-provisioning-app#149] opened 2019-06-19 11:02 UTC
At provisioning there are objects created in multiple locations: Bitbucket, Openshift, Jenkins, etc. There should be a functionality to correctly and accurately remove a provisioned app from the environment.

**Comment by rattermeyer** [comment] 2019-06-26 11:37
We left this out intentionally in the first run. This allows the provisioning app to be used as a self-provisioning tool by "normal" developers. Some functionality (for OpenShift) is available as jobs in rundeck already. 
If we include it, we probably should think about a roles concept as well.

**Comment by clemensutschig** [comment] 2019-06-26 12:53
I'd suggest only admins can do this ... ?! .. or we stick with the rundeck only approach for now

**Comment by tbugfinder** [comment] 2019-07-08 20:05
Usually this ends up in a left-overs and dead projects.
At least scripts should be shared so that ODS-users can remove even partially deployed projects.

**Comment by clemensutschig** [comment] 2019-07-09 04:43
@tbugfinder i agree.. currently prov App goes thru major refactoring... i'll try to take this up for 2.0.. want to help?

**Comment by clemensutschig** [comment] 2019-07-18 14:59
@thowerner  - the backbone is part of 1.2 release - we are still unsure of the UI, but intend to make this happen for 2.0

**Comment by serverhorror** [comment] 2020-10-12 15:54
This is getting more and more of an issue, our namespaces are kind of cluttered with things we want to get rid of :(

**Comment by michaelsauter** [comment] 2020-10-20 10:20
Check https://github.com/opendevstack/ods-core/blob/master/delete-components/Jenkinsfile. Getting rid of components in OpenShift is relatively straight-forward. For Bitbucket, afaik it is just deleting the repo. Jira might have a component as well that you need to delete (depends on when your component was provisioned), and Confluence should not have anything related to the component.

**Comment by serverhorror** [comment] 2020-10-20 13:24
> Check https://github.com/opendevstack/ods-core/blob/master/delete-components/Jenkinsfile. Getting rid of components in OpenShift is relatively straight-forward. For Bitbucket, afaik it is just deleting the repo. Jira might have a component as well that you need to delete (depends on when your component was provisioned), and Confluence should not have anything related to the component.

The problem is the provisioning app. I can't remove and reuse a name that has been used. Or even reuse a name from the prov app at all.

**Comment by michaelsauter** [comment] 2020-10-21 06:49
@serverhorror True, there is no way for a user to do that right now. Someone with access to the prov app pod needs to clean up a file in there. I thought you just wanted to get rid of stuff, not reuse the same name.

**Comment by stitakis** [comment] 2020-10-21 07:25
@serverhorror an API for the removal of components is in "place" (https://github.com/opendevstack/ods-provisioning-app/blob/13f626ce59f48bc090ef7c234322d249700225eb/src/main/java/org/opendevstack/provision/controller/ProjectApiController.java#L871) but currently:
A. not enabled in the UI 
B. can only be called by an administrator.

Is not supported in the current UI because we haven't had enough time to "add a button" and test it for the ODS 3.0 release. Additionally is not clear what should happens with the BitBucket repo and/or if we need a 4-eyes-check process or "undo" button to restore it. :-)

If this missing feature is blocking you somehow, maybe we can talk with an admin (@segator) and try an curl request against the  api. Sounds good?

**Comment by serverhorror** [comment] 2020-11-24 18:42
@stitakis This is more a problem for adoption. People are reluctant to play around and give ODS a chance to even work because they are afraid they might not be able to just get rid of whatever they tried.

So in a sense,

* yes it is "blocking" because users aren't even considering ODS because of that (I know that seems like a minor issue, apparently it is important to the user group we are dealing with)
* no it is not blocking because internal support teams can remove this (but see above; the friction this creates keeps larger audiences from adopting ODS in the first place)

**Comment by stitakis** [comment] 2020-11-25 08:06
@serverhorror I think you make the point clear... adoption is a key aspect for us. I'll have scheduled this item for next release ODS 4.x. Unfortunately is the earliest that we can deliver it. I think in the meanwhile we can coordinate with @segator to get rid of components using the api and announce this kind of solution in our chat. @Sounds good?

**Comment by serverhorror** [comment] 2020-12-03 17:25
@stitakis Thank you!

As long as I can tell people "not yet but you will be able to do that" I have a UART hat I can use :)

**Comment by nichtraunzer** [comment] 2021-01-25 09:45
> @stitakis This is more a problem for adoption. People are reluctant to play around and give ODS a chance to even work because they are afraid they might not be able to just get rid of whatever they tried.
> 
> So in a sense,
> 
> * yes it is "blocking" because users aren't even considering ODS because of that (I know that seems like a minor issue, apparently it is important to the user group we are dealing with)
> * no it is not blocking because internal support teams can remove this (but see above; the friction this creates keeps larger audiences from adopting ODS in the first place)

I second that ... good point

**Comment by stitakis** [comment] 2021-02-15 09:37
This functionality is implemented in the new front end, which will be deployed in next release. I'm closing this item.

**Closed by stitakis** 2021-02-15 09:37 UTC
Labels: enhancement
