### ISSUE TITLE
Sporadic error from mail rendering

### ISSUE THREAD

**Issue by michaelsauter** [opendevstack/ods-provisioning-app#10] opened 2018-08-09 06:33 UTC
We have seen the following a few times now:

```
Can not update project, error Could not prepare mail; nested exception is
org.thymeleaf.exceptions.TemplateProcessingException:
Link base "jenkins-foo-cd.22ad.bar.openshiftapps.com" cannot be context relative (/) or
page relative unless you implement the org.thymeleaf.context.IWebContext interface
(context is of class: org.thymeleaf.context.Context) (mailTemplate:39)
```

It does not happen all the time, so not sure what the cause is.

**Comment by michaelsauter** [comment] 2018-08-09 06:36
FYI @ManuelFeller

**Comment by clemensutschig** [comment] 2018-08-09 07:01
@michaelsauter  - this is a known issue - if you provisioned an app a while ago - in this case the openshift url - such as jenkins-foo-cd.22ad.bar.openshiftapps.com is w/o protocol ... in the prov-history storage (go to pod - cd opt/provision/history/ and into the *project.txt) .. - just add the protocol - closing as not a bug

**Closed by clemensutschig** 2018-08-09 07:01 UTC
Labels: bug

**Comment by michaelsauter** [comment] 2018-08-09 07:08
Oh, great to know! @ManuelFeller I added the protocol in the pod for you. Next provisioning should work then.
