### ISSUE TITLE
Provision project specific quickstarters

### ISSUE THREAD

**Issue by stitakis** [opendevstack/ods-provisioning-app#417] opened 2020-04-09 09:23 UTC
**Is your feature request related to a problem? Please describe.**
Currently, quickstarters definition is hardcoded in the application properties.
This makes difficult to developers to make available their own quickstarters.

**Describe the solution you'd like**
Enable ProvApp to provision quickstarters that are hosted in the project git server from a specific/default quickstarters git repository.

**Comment by stitakis** [comment] 2020-04-09 09:24
@metmajer does this cover the requirements coming from the project team?

**Comment by michaelsauter** [comment] 2020-04-09 10:39
This is probably related to (or even a duplicate of) https://github.com/opendevstack/ods-provisioning-app/issues/363.

We need to figure out how the quickstarters should be configured if they are not. defined in `application.properties` (and I totally agree they should not be defined there). What do you have in mind for it?

FYI @oalyman

**Comment by stitakis** [comment] 2020-04-09 12:26
@michaelsauter I bit different that #363 by related... actually #363 could be fixed by this proposal.

What I have in mind is to:
1. specify a quickstarters yml definition

2. read the quickstarters yml definition from a repository.
Here the repository is 
A. by convention a git repo repo called "quickstarters" which is located in the project git repository
or
B. the project admin configures (overwrites) in the UI the name of project quickstarters or the git repository url. (to access that repo either the user credentials are used or the project cd_user)

3. quickstarters repo not only includes quickstarters yml definition but the quickstarters code too

**Comment by michaelsauter** [comment] 2020-04-09 13:21
I'm not sure I understand your third point. Can you explain?

Also, out of interest, why create a separate repo just for one YAML file? Is there a specific reason? One could also imagine just mounting a file or so ... (or reading, as #363 proposes, from a ConfigMap not controlled by Tailor).

**Comment by stitakis** [comment] 2020-04-20 07:07
I see, I didn't phrase point 3 properly... make this sense to you?

3. include quickstarters code in the repository that contains the quickstarters.yml.

To summarize... 
- just one quickstarter YAML file per quickstarters repository. 
- the idea is to give team the posibility to create a quickstarters repository per project. 
- the configuration will be located in a quickstarters.yml file in the root folder of the quickstarters project.

**Comment by michaelsauter** [comment] 2020-04-20 08:06
Ok, I understood now that this is about quickstarters useable ONLY by one project. Instead of quickstarters usable by many projects but ONLY by one installation (which is what #363 relates to).

I don't understand the use case of this though. A quickstarter is only worthwhile, if I need to do the same "setup" 20, 30, 100 times ... if I do the same "setup" only a few times, it is not worth building and maintaining a quickstarter. Why a project would create and use its own quickstarters is not clear to me. If they have lots of repos that should be the same, they could use a simple script that they run after creating a naked component with the docker-plain quickstarter.

@metmajer Could you explain the use case if I am missing it completely here?

Otherwise I would suggest to close this.

**Comment by michaelsauter** [comment] 2020-04-20 14:23
On a side note, if users want to simply try a non-supported quickstarter that is available somewhere in the Bitbucket instance, it can be done e.g. by using the script provided in https://github.com/BIX-Digital/ods-contrib/tree/master/quickstart-with-jenkins.

**Comment by serverhorror** [comment] 2020-11-24 18:37
Can't we just paste a link to a git repo and [cookiecutter ](https://cookiecutter.readthedocs.io/en/1.7.2/) (or similar) would be a supported format, even "just" a git repo with the ODS native format that I can pull would be nice!

**Comment by michaelsauter** [comment] 2020-11-25 07:55
Please also note there is already documentation on how to author quickstarters at https://www.opendevstack.org/ods-documentation/opendevstack/3.x/quickstarters/authoring-quickstarters.html. @serverhorror please extend this if you think this is not sufficient.

I'm going to close this now, as we probably don't want/need this feature. What we might need is a better template / better documentation, which can be a new issue / PR.

**Closed by michaelsauter** 2020-11-25 07:55 UTC
Labels: enhancement

**Comment by stitakis** [comment] 2020-11-25 08:15
@michaelsauter I have the feeling that we haven't explored/discussed this enough, but also think is fine to close it... we can always reopen it.

**Comment by serverhorror** [comment] 2020-12-03 17:23
@michaelsauter I think the docs are good. I'm referring to:

1. I'm a user in front of the prov app and
1. have have a git link from someone.
1. That's an ODS quickstarter.
1. I don't have admin permissions in ODS.
1. I want to use that quickstarter

I might have been in the wrong ticket. We have a ton of components and no control over ODS but have to modify every single component after provisioning with a few proprietary code snippets. 

> Usually, quickstarters are triggered through the provisioning app. However, in order to try a new quickstarter, or to try changes to an existing quickstarter which are made in a branch, you can use the quickstart-with-jenkins/run.sh script in the BIX-Digital/ods-contrib repository to provision a quickstarter without registering it with the provisioning app. See its help for usage.

I was referring to: _How do I do that without going to a 3rd-party repo and just use a quickstarter that is not registered?_

**Comment by michaelsauter** [comment] 2020-12-04 07:14
@serverhorror Got you. The steps you are describing were thought about but we did not implement them back then out of caution. I would be OK to rethink this as the code is anyway executed in your own Jenkins instance. But it feels like something which we should give some time and thought before allowing it. I suggest you open a new issue and describe exactly what your use case is.
