### ISSUE TITLE
Provisioning app fails to clean up failed provisioning attempt

### ISSUE THREAD

**Issue by sklingel** [opendevstack/ods-provisioning-app#267] opened 2019-11-07 16:45 UTC
**Describe the bug**
Provisioning app fails to clean up because of failed rundeck Job. Jira project is not being removed

**Expected behavior**
No artifacts present after error downstream (e.g in rundeck)

**Log Output (ensure to remove any confidential information like tokens, project names, etc.**
```
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepared request: [Request{method=DELETE, url=******rest/api/space/***, 
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.SimpleCookieJar - Load cookies for host[****]                                                   
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.provision.util.rest.RestClient - URL: *****, method: DELETE, response-code: 202, r
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.services.ConfluenceAdapter - Cleanup done - status: 0 components are left ..                                                
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.provision.services.JiraAdapter - Cleaning up bugtracker space: *** with url ****              
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepare request for execution                                                                    
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - The request has no body                                                                          
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepared URL [***/permissionscheme]             
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepared request: [Request{method=GET, url=******
2019-11-07 06:22:23 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.SimpleCookieJar - Load cookies for host[****]                                                         
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.provision.util.rest.RestClient - URL: *****/permissionscheme, method: GET, resp
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.provision.services.JiraAdapter - Cleaning up permissionset 15142 *** PERMISSION SCHEME                                        
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepare request for execution                                                                    
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - The request has no body                                                                          
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepared URL [*****]                   
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.RestClientCall - Prepared request: [Request{method=DELETE, url=******/rest/api/latest/permission
2019-11-07 06:22:25 loggerFileName=*** [*****] DEBUG o.o.p.util.rest.SimpleCookieJar - Load cookies for host[****]                                                         
2019-11-07 06:22:27 loggerFileName=*** [*****] ERROR o.o.provision.util.rest.RestClient - Call failed:                                                                                 
org.opendevstack.provision.util.exception.HttpException: Could not DELETE > ***** : {"errorMessages":["Scheme 15,142 has associated projects
        at org.opendevstack.provision.util.rest.RestClient.execute(RestClient.java:51)                                       

```

**Additional context**

**Comment by clemensutschig** [comment] 2019-11-08 08:47
the problem is the permission set hooked to the jira project - we need to clean the jira project first, and then the permission set.. It's somewhat odd - I am sure we tested this with @tjaeschke  - before we merged :(

**Closed** 2019-11-15 10:41 UTC
Labels: bug
